CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  rola TEXT NOT NULL DEFAULT 'USER' CHECK(rola IN ('USER','ADMIN')),
  created_at TEXT DEFAULT (datetime('now'))
);